Output demo.gif

Set FontSize 30
Set Width 1600
Set Height 1200
Set TypingSpeed 100ms

Type "./osc-time-trigger"
Enter
Sleep 500ms
Set TypingSpeed 200ms
Type "h"
Type "127.0.0.1"
Enter
Type "p"
Backspace 1 
Type "8765"
Enter
Type "t"
Sleep 1s
Type "/composition/columns/300/connect"
Enter
Sleep 1s
Type "18:35:00"
Enter
Type "t"
Enter
Left 4
Backspace 1
Type "4"
Enter
Sleep 3s
Down
Sleep 1s
Type "d"
Sleep 2s
Type "s"
Sleep 4s
Type "q"
Sleep 1s
